# Generated by Django 5.0.6 on 2024-06-30 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(choices=[('default', 0), ('minimum', 10), ('maximum', 100), ('full', 110)], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=170)),
                ('text_post', models.TextField()),
                ('rating', models.IntegerField(choices=[('default', 0), ('minimum', 10), ('maximum', 100), ('full', 110)], default=0)),
                ('date_creation', models.DateTimeField()),
                ('publication_type', models.CharField(choices=[('article', 'article'), ('news', 'news')], default='news', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='np_post.author')),
                ('category', models.ManyToManyField(to='np_post.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comm', models.TextField()),
                ('data_add_comm', models.DateTimeField()),
                ('rating', models.IntegerField(choices=[('default', 0), ('minimum', 10), ('maximum', 100), ('full', 110)], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='np_post.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='np_post.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='np_post.post')),
            ],
        ),
    ]
