# Generated by Django 5.0.6 on 2024-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_post', '0002_alter_comment_data_add_comm_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.IntegerField(blank=True, choices=[('default', 0), ('minimum', 10), ('maximum', 100), ('full', 110)], default=0, null=True),
        ),
    ]
