# Generated by Django 5.0.6 on 2024-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_post', '0003_alter_author_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
