# Generated by Django 5.0.6 on 2024-08-14 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_post', '0009_alter_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='cats_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
