# Generated by Django 5.0.6 on 2024-08-07 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('np_post', '0007_alter_post_publication_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(blank=True, related_name='subs_category', to='np_post.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subs_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
